version: 2.1

jobs:
  license_chk:
    machine:
      # need machine as want to mount a volume
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: Execute skywalking-eyes check of licenses
          # once 0.2.0 released change image
          command: |
            set -e
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker run --rm -v $(pwd):/github/workspace ghcr.io/apache/skywalking-eyes/license-eye header check
  build_docker:
    machine:
      image: ubuntu-2004:202107-02
    environment:
      IMAGE_NAME: quay.io/wtsicgp/c-sar
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Building CI image
          command: |
            set -e
            LC_REPO=$(echo $CIRCLE_PROJECT_REPONAME | tr '[:upper:]' '[:lower:]')
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker build -f Dockerfile -t $LC_REPO:$CIRCLE_SHA1 .
            BRANCH_OR_TAG="${CIRCLE_TAG:-$CIRCLE_BRANCH}"
            CLEAN_BRANCH=$(echo $BRANCH_OR_TAG | tr / -)
            if [ "$CIRCLE_TAG" = "$BRANCH_OR_TAG" ]; then
              docker tag ${LC_REPO}:${CIRCLE_SHA1} $IMAGE_NAME:$CLEAN_BRANCH
              echo "$QUAYIO_PASSWORD" | docker login -u "$QUAYIO_USER" --password-stdin quay.io
              echo 'Pushing image'
              docker push $IMAGE_NAME:$CLEAN_BRANCH
            else
              echo "I am not a tag so not pushing image"
            fi

workflows:
  version: 2.1
  build_test_publish:
    jobs:
      - license_chk:
          context:
            - dockerhub-casmservice
      - build_docker:
          context:
            - dockerhub-casmservice
            - quayio-casmservice
          requires:
            - license_chk
          filters:
            tags:
              only: /.+/
